#!/bin/sh

weasels="many|various|very|fairly|several|extremely\
|exceedingly|quite|remarkably|few|surprisingly\
|mostly|largely|huge|tiny|((are|is) a number)\
|excellent|interestingly|significantly\
|substantially|clearly|vast|relatively|completely"
 
wordfile=""
 
# Check for an alternate weasel file
wordfile="~/.weasels"
if [ -f $wordfile ]; then
    for w in `cat $wordfile`; do
        weasels="$weasels|$w"
    done
fi
 
egrep -i -n --color "\\b($weasels)\\b" $*
 
exit $?
