.\" man page for the dupwords utility.
.Dd July 24, 2010
.Dt DUPWORDS 1
.Os
.Sh NAME
.Nm dupwords
.Nd Spot duplicated words
.Sh SYNOPSIS
.Nm
.Ar file...
.Sh DESCRIPTION
The dupwords utility looks for duplicated words in its input, and reports each line number and duplicated word in its output.
Input can come from either a list of file arguments or stdin.
.Sh OPTIONS
None
.Sh SEE ALSO
aspell(1), passive(1), proofread(1), weasels(1)
.Sh AUTHOR
Sterling (Chip) Camden <sterling@camdensoftware.com>, adapted from Matt Might
.Sh WWW
<http://chipstips.com/?tag=rbproofread>
<http://matt.might.net/articles/shell-scripts-for-passive-voice-weasel-words-duplicates/>
.Sh BUGS
None known.
