.\" man page for the passive utility.
.Dd July 24, 2010
.Dt PASSIVE 1
.Os
.Sh NAME
.Nm passive
.Nd Detect passive voice
.Sh SYNOPSIS
.Nm
.Ar file...
.Sh DESCRIPTION
The passive utility detects the passive voice in English input and highlights those occurrences in its ouput.
Input can come from either a list of file arguments or stdin.
.Sh OPTIONS
None
.Sh SEE ALSO
aspell(1), dupwords(1), proofread(1), weasels(1)
.Sh AUTHOR
Sterling (Chip) Camden <sterling@camdensoftware.com>, adapted from Matt Might
.Sh WWW
<http://chipstips.com/?tag=rbproofread>
<http://matt.might.net/articles/shell-scripts-for-passive-voice-weasel-words-duplicates/>
.Sh BUGS
None known.
